server:
  port: ${port}
  forward-headers-strategy: FRAMEWORK
app:
  app_key: ${appKey}
  app_secret: ${appSecret}
  corp_id: ${corpId}
  agent_id: ${agentId}
  # 域名, 请与内网穿透工具使用的域名一致。
  domain: ${domain}

